ifeq (.private, $(wildcard .private))
	PRIVATE = 1
endif

bootstrap: setup secrets

setup:
	brew update
	brew bundle install
	# Virtual macOS environments of GitHub Actions might have SwiftLint preinstalled
	which swiftlint &>/dev/null || brew bundle install swiftlint
	bundle update
	bundle config set --local path vendor/bundle
	bundle install

secrets:
ifdef PRIVATE
	@echo "// This is generated by \`make secrets\`. Don't edit.\nlet clientId = \"$(CLIENT_ID)\"\nlet clientSecret = \"$(CLIENT_SECRET)\"" > NimbleSurvey/Sources/Secrets/Secrets.swift
else
	@cp NimbleSurvey/Sources/Secrets/Secrets.swift.example NimbleSurvey/Sources/Secrets/Secrets.swift
endif

private:
	@touch .private
